### ISSUE TITLE
Relax binary and bytestring upper-bounds

### ISSUE THREAD

**Issue by pbrisbin** [freizl/hoauth2#142]
I'm able to compile my `yesod-auth-oauth2` package on lts-19 / nightly and GHC 9.2 with the following `stack.yaml`:

```yaml
resolver: 2022-03-25

extra-deps:
  - hoauth2-2.3.0
  - yesod-auth-1.6.11
  - yesod-core-1.6.22.0
  - yesod-form-1.7.0
  - yesod-persistent-1.6.0.7

# binary-0.8.9.0 and bytestring-0.11.3.0 are too new for hoauth2-2.3.0
allow-newer: true
```

I believe that means `hoauth2-2.3.0` is all set to be re-enabled in Stackage too, except for the upper-bounds on `binary` and `bytestring`.

Could you make a release or revision that relaxes them?
